# Generated by Django 5.1.4 on 2025-02-19 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('provincia', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaClc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('razon_social', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(max_length=100)),
                ('representante_legal', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Empresa CLC',
                'verbose_name_plural': 'Empresas CLC',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('proveedores', models.CharField(blank=True, max_length=100)),
                ('country_origin', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('contact_info', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pandora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Procedencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Procesos_auditados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('objeto', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Procesos Auditados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('direccion1', models.TextField()),
                ('direccion2', models.TextField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_primario', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Cliente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Contratación',
                'verbose_name_plural': 'Tipos de Contratación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('cobertura', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Zonas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('level', models.IntegerField(default=0)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pandora.categorias')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('alias', models.CharField(max_length=30, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.ciudades')),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.tipocliente')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.zonas')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MsPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=50)),
                ('nombre_generico', models.CharField(max_length=250)),
                ('normada', models.BooleanField()),
                ('referencias_tecnica', models.TextField()),
                ('aplicaciones', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.categorias')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.especialidades')),
            ],
            options={
                'verbose_name': 'MS Pref',
                'verbose_name_plural': 'MS Prefs',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='PreciosSie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.TextField(blank=True, null=True)),
                ('fecha_sie', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.clientes')),
                ('pandora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.pandora')),
                ('detalle_sie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.procesos_auditados')),
            ],
            options={
                'verbose_name': 'Precio SIE',
                'verbose_name_plural': 'Precios SIE',
                'ordering': ['-fecha_sie', 'pandora'],
            },
        ),
        migrations.CreateModel(
            name='CostosPandora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.marca')),
                ('pandora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.pandora')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.proveedores')),
            ],
            options={
                'verbose_name': 'Costo Pandora',
                'verbose_name_plural': 'Costos Pandora',
                'ordering': ['-fecha', 'pandora'],
            },
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.proveedores')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
