# Generated by Django 5.1.4 on 2025-03-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0001_initial'),
        ('products', '0012_rename_empresa_historialdeventas_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciossie',
            name='producto_disponible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precios_sie_disponibles', to='products.productodisponible', verbose_name='Producto Disponible'),
        ),
        migrations.AddField(
            model_name='preciossie',
            name='producto_ofertado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precios_sie_ofertados', to='products.productoofertado', verbose_name='Producto Ofertado'),
        ),
        migrations.DeleteModel(
            name='CostosPandora',
        ),
    ]
