# Generated by Django 5.1.4 on 2025-03-23 04:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0003_contactos'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RelacionesBlue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel', models.IntegerField(help_text='Valor numérico entre 1 y 9', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_blue', to='pandora.clientes')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_blue', to='pandora.contactos')),
            ],
            options={
                'verbose_name': 'Relación Blue',
                'verbose_name_plural': 'Relaciones Blue',
                'db_table': 'relaciones_blue',
                'unique_together': {('cliente', 'contacto')},
            },
        ),
    ]
