# Generated by Django 5.1.4 on 2025-02-24 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosOfertados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('cudim', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('referencias', models.TextField(blank=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pandora.categorias')),
            ],
            options={
                'verbose_name': 'Producto Ofertado',
                'verbose_name_plural': 'Productos Ofertados',
            },
        ),
        migrations.CreateModel(
            name='ProductosDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('tz_oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tz_demanda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tz_inflacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tz_calidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tz_eficiencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tz_referencial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_referencial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_sie_referencial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_sie_tipob', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta_privado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pandora.categorias')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pandora.marca')),
                ('id_producto_ofertado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productosofertados')),
            ],
            options={
                'verbose_name': 'Producto Disponible',
                'verbose_name_plural': 'Productos Disponibles',
            },
        ),
    ]
