# Generated by Django 5.1.4 on 2025-02-24 04:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0001_initial'),
        ('products', '0002_productosofertados_productosdisponibles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('nombre', models.CharField(max_length=200, verbose_name='Name')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('presentacion', models.CharField(blank=True, max_length=100, verbose_name='Presentation')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('tz_oferta', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Supply Rating')),
                ('tz_demanda', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Demand Rating')),
                ('tz_inflacion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Inflation Rating')),
                ('tz_calidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Quality Rating')),
                ('tz_eficiencia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Efficiency Rating')),
                ('tz_referencial', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Reference Rating')),
                ('costo_referencial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Reference Cost')),
                ('precio_sie_referencial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SIE Reference Price')),
                ('precio_sie_tipob', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SIE Type B Price')),
                ('precio_venta_privado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Private Sale Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Available Product',
                'verbose_name_plural': 'Available Products',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoOfertado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('cudim', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='CUDIM')),
                ('nombre', models.CharField(max_length=200, verbose_name='Name')),
                ('descripcion', models.TextField(blank=True, verbose_name='Description')),
                ('especialidad', models.CharField(blank=True, max_length=100, verbose_name='Specialty')),
                ('referencias', models.TextField(blank=True, verbose_name='References')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Offered Product',
                'verbose_name_plural': 'Offered Products',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='productosdisponibles',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='productosdisponibles',
            name='id_marca',
        ),
        migrations.RemoveField(
            model_name='productosdisponibles',
            name='id_producto_ofertado',
        ),
        migrations.RemoveField(
            model_name='productosofertados',
            name='id_categoria',
        ),
        migrations.AlterModelOptions(
            name='productdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Product Document', 'verbose_name_plural': 'Product Documents'},
        ),
        migrations.AddField(
            model_name='productdocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='productdocument',
            index=models.Index(fields=['document_type'], name='products_pr_documen_7d18e1_idx'),
        ),
        migrations.AddIndex(
            model_name='productdocument',
            index=models.Index(fields=['uploaded_at'], name='products_pr_uploade_caf575_idx'),
        ),
        migrations.AddField(
            model_name='productodisponible',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_disponibles_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='productodisponible',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pandora.categorias', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='productodisponible',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pandora.marca', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='productodisponible',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_disponibles_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='productoofertado',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_ofertados_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='productoofertado',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pandora.categorias', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='productoofertado',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_ofertados_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='productodisponible',
            name='id_producto_ofertado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_disponibles', to='products.productoofertado', verbose_name='Offered Product'),
        ),
        migrations.DeleteModel(
            name='ProductosDisponibles',
        ),
        migrations.DeleteModel(
            name='ProductosOfertados',
        ),
        migrations.AddIndex(
            model_name='productoofertado',
            index=models.Index(fields=['code'], name='products_pr_code_3a1572_idx'),
        ),
        migrations.AddIndex(
            model_name='productoofertado',
            index=models.Index(fields=['cudim'], name='products_pr_cudim_1543a2_idx'),
        ),
        migrations.AddIndex(
            model_name='productodisponible',
            index=models.Index(fields=['id_categoria'], name='products_pr_id_cate_092950_idx'),
        ),
        migrations.AddIndex(
            model_name='productodisponible',
            index=models.Index(fields=['id_producto_ofertado'], name='products_pr_id_prod_ae5f07_idx'),
        ),
        migrations.AddIndex(
            model_name='productodisponible',
            index=models.Index(fields=['code'], name='products_pr_code_d8c9c6_idx'),
        ),
    ]
