# Generated by Django 5.1.4 on 2025-02-24 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productodisponible_productoofertado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Document', 'verbose_name_plural': 'Product Documents'},
        ),
        migrations.RemoveIndex(
            model_name='productdocument',
            name='products_pr_uploade_caf575_idx',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='change_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='productchange',
            old_name='changed_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='productdocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='relatedproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productchange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='relatedproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='productdocument',
            index=models.Index(fields=['created_at'], name='products_pr_created_be120f_idx'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(fields=('product', 'price_list'), name='unique_product_price_list'),
        ),
        migrations.AddConstraint(
            model_name='relatedproduct',
            constraint=models.UniqueConstraint(fields=('product', 'related_product', 'relationship_type'), name='unique_related_product_relationship'),
        ),
    ]
