# Generated by Django 5.1.4 on 2025-02-27 00:03

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productodisponible',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto disponible', 'verbose_name_plural': 'Productos disponibles'},
        ),
        migrations.AlterModelOptions(
            name='productoofertado',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto Ofertado', 'verbose_name_plural': 'Productos Ofertados'},
        ),
        migrations.CreateModel(
            name='ImagenReferenciaProductoOfertado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(help_text='Imagen de referencia para el producto', upload_to=products.models.producto_ofertado_imagen_path, verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización de la imagen', verbose_name='Orden')),
                ('is_primary', models.BooleanField(default=False, help_text='Marca esta imagen como la principal para el producto', verbose_name='Es imagen principal')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_referencia_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('producto_ofertado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='products.productoofertado', verbose_name='Producto Ofertado')),
            ],
            options={
                'verbose_name': 'Imagen de Referencia',
                'verbose_name_plural': 'Imágenes de Referencia',
                'ordering': ['orden', 'created_at'],
            },
        ),
    ]
