# Generated by Django 5.1.4 on 2025-02-27 07:31

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productodisponible_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProductoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.FileField(help_text='Documento PDF del producto (manual, ficha técnica, etc.)', upload_to=products.models.producto_disponible_documento_path, verbose_name='Documento')),
                ('tipo_documento', models.CharField(choices=[('manual', 'Manual de Usuario'), ('ficha_tecnica', 'Ficha Técnica'), ('certificado', 'Certificado'), ('catalogo', 'Catálogo'), ('otros', 'Otros')], default='otros', max_length=50, verbose_name='Tipo de Documento')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=True, help_text='Indica si el documento es público o solo para uso interno', verbose_name='Es público')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_producto_disponible_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('producto_disponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_producto', to='products.productodisponible', verbose_name='Producto Disponible')),
            ],
            options={
                'verbose_name': 'Documento de Producto Disponible',
                'verbose_name_plural': 'Documentos de Productos Disponibles',
                'ordering': ['tipo_documento', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProductoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(help_text='Imagen del producto disponible', upload_to=products.models.producto_disponible_imagen_path, verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización de la imagen', verbose_name='Orden')),
                ('is_primary', models.BooleanField(default=False, help_text='Marca esta imagen como la principal para el producto', verbose_name='Es imagen principal')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_producto_disponible_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('producto_disponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_producto', to='products.productodisponible', verbose_name='Producto Disponible')),
            ],
            options={
                'verbose_name': 'Imagen de Producto Disponible',
                'verbose_name_plural': 'Imágenes de Productos Disponibles',
                'ordering': ['orden', 'created_at'],
            },
        ),
    ]
