# Generated by Django 5.1.4 on 2025-03-04 05:40

import django.core.validators
import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0001_initial'),
        ('products', '0006_documentoproductodisponible_imagenproductodisponible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productodisponible',
            name='costo_referencial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Referencial'),
        ),
        migrations.AlterField(
            model_name='productodisponible',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pandora.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='productodisponible',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modolo'),
        ),
        migrations.AlterField(
            model_name='productodisponible',
            name='precio_sie_referencial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SIE Precio Referencial'),
        ),
        migrations.AlterField(
            model_name='productodisponible',
            name='presentacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Presentacion'),
        ),
        migrations.AlterField(
            model_name='productodisponible',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='productodisponible',
            name='tz_calidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Taza de calidad'),
        ),
        migrations.AlterField(
            model_name='productodisponible',
            name='tz_demanda',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Taza de demanda'),
        ),
        migrations.AlterField(
            model_name='productodisponible',
            name='tz_eficiencia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Taza de eficiencia'),
        ),
        migrations.AlterField(
            model_name='productodisponible',
            name='tz_inflacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Taza de inflacion'),
        ),
        migrations.AlterField(
            model_name='productodisponible',
            name='tz_oferta',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Taza de Oferta'),
        ),
        migrations.AlterField(
            model_name='productodisponible',
            name='tz_referencial',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Taza de Referencia'),
        ),
        migrations.CreateModel(
            name='DocumentoProductoOfertado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento', models.FileField(help_text='Documento PDF del producto (manual, ficha técnica, etc.)', upload_to=products.models.producto_ofertado_documento_path, verbose_name='Documento')),
                ('tipo_documento', models.CharField(choices=[('manual', 'Manual de Usuario'), ('ficha_tecnica', 'Ficha Técnica'), ('certificado', 'Certificado'), ('catalogo', 'Catálogo'), ('otros', 'Otros')], default='otros', max_length=50, verbose_name='Tipo de Documento')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=True, help_text='Indica si el documento es público o solo para uso interno', verbose_name='Es público')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_producto_ofertado_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('producto_ofertado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_producto', to='products.productoofertado', verbose_name='Producto Ofertado')),
            ],
            options={
                'verbose_name': 'Documento de Producto Ofertado',
                'verbose_name_plural': 'Documentos de Productos Ofertados',
                'ordering': ['tipo_documento', 'titulo'],
            },
        ),
    ]
