# Generated by Django 5.1.4 on 2025-03-04 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0001_initial'),
        ('products', '0007_alter_productodisponible_costo_referencial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productodisponible',
            name='procedencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pandora.procedencia', verbose_name='Procedencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productodisponible',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pandora.unidades', verbose_name='Presentacion'),
        ),
        migrations.CreateModel(
            name='HistorialDeCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('factura', models.CharField(max_length=100, unique=True, verbose_name='Factura')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.proveedores', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Historial de Compra',
                'verbose_name_plural': 'Historiales de Compras',
                'ordering': ['-fecha'],
            },
        ),
    ]
