# Generated by Django 5.1.4 on 2025-03-04 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0001_initial'),
        ('products', '0008_productodisponible_procedencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDeVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('factura', models.CharField(max_length=100, unique=True, verbose_name='Factura')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.clientes', verbose_name='Proveedor')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandora.empresaclc', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Historial de Ventas',
                'verbose_name_plural': 'Historiales de Ventas',
                'ordering': ['-fecha'],
            },
        ),
    ]
