# Generated by Django 5.1.4 on 2025-03-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_historialdeventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='product',
            name='procedencia',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unidades',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='relatedproduct',
            name='related_product',
        ),
        migrations.RemoveField(
            model_name='productchange',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productdocument',
            name='product',
        ),
        migrations.RemoveField(
            model_name='relatedproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productchange',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='productdocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
        migrations.DeleteModel(
            name='RelatedProduct',
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductChange',
        ),
        migrations.DeleteModel(
            name='ProductDocument',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
