# Generated by Django 5.1.4 on 2025-03-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_historialdeventas'),
    ]

    operations = [
        # Empty operations to avoid errors
    ]
