# Generated by Django 5.1.4 on 2025-03-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_productprice_price_list_and_more'),
    ]

    operations = [
        # Add cantidad field to HistorialDeVentas
        migrations.AddField(
            model_name='historialdeventas',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]