# Generated by Django 5.1.4 on 2025-03-06 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0001_initial'),
        ('products', '0011_add_historial_compras_and_update_ventas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialdeventas',
            old_name='Empresa',
            new_name='empresa',
        ),
        migrations.RemoveField(
            model_name='historialdeventas',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='historialdecompras',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='historialdecompras',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pandora.empresaclc', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialdecompras',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='products.productodisponible', verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialdeventas',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='products.productodisponible', verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialdeventas',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pandora.clientes', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
