# Generated by Django 5.1.4 on 2025-03-17 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productprice_price_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('producto_disponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.productodisponible', verbose_name='Producto Disponible')),
            ],
            options={
                'verbose_name': 'Precio de Producto',
                'verbose_name_plural': 'Precios de Productos',
                'ordering': ['producto_disponible'],
            },
        ),
    ]
