# Generated by Django 5.1.4 on 2025-03-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtrasInstituciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('usuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('representante', models.CharField(max_length=255)),
                ('institucion', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Otra Institución',
                'verbose_name_plural': 'Otras Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Sercop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('usuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('representante', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SERCOP',
                'verbose_name_plural': 'SERCOP',
            },
        ),
        migrations.CreateModel(
            name='Sri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('usuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('representante', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SRI',
                'verbose_name_plural': 'SRI',
            },
        ),
        migrations.CreateModel(
            name='Supercom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('usuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('representante', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Supercom',
                'verbose_name_plural': 'Supercom',
            },
        ),
    ]
