# Generated by Django 5.1.4 on 2025-03-07 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blegal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otrasinstituciones',
            options={'ordering': ['institucion', '-fecha_actualizacion'], 'verbose_name': 'Otra Institución', 'verbose_name_plural': 'Otras Instituciones'},
        ),
        migrations.AlterModelOptions(
            name='sercop',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'SERCOP', 'verbose_name_plural': 'SERCOP'},
        ),
        migrations.AlterModelOptions(
            name='sri',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'SRI', 'verbose_name_plural': 'SRI'},
        ),
        migrations.AlterModelOptions(
            name='supercom',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'SUPERCOM', 'verbose_name_plural': 'SUPERCOM'},
        ),
        migrations.AddField(
            model_name='otrasinstituciones',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='otrasinstituciones',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='sercop',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='sercop',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='sri',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='sri',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='supercom',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='supercom',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='otrasinstituciones',
            name='contrasena',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='otrasinstituciones',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='otrasinstituciones',
            name='empresa',
            field=models.CharField(max_length=255, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='otrasinstituciones',
            name='institucion',
            field=models.CharField(max_length=255, verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='otrasinstituciones',
            name='representante',
            field=models.CharField(max_length=255, verbose_name='Representante'),
        ),
        migrations.AlterField(
            model_name='otrasinstituciones',
            name='ruc',
            field=models.CharField(max_length=13, unique=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='otrasinstituciones',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='otrasinstituciones',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='otrasinstituciones',
            name='usuario',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='sercop',
            name='contrasena',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='sercop',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='sercop',
            name='empresa',
            field=models.CharField(max_length=255, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='sercop',
            name='representante',
            field=models.CharField(max_length=255, verbose_name='Representante'),
        ),
        migrations.AlterField(
            model_name='sercop',
            name='ruc',
            field=models.CharField(max_length=13, unique=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='sercop',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='sercop',
            name='usuario',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='sri',
            name='contrasena',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='sri',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='sri',
            name='empresa',
            field=models.CharField(max_length=255, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='sri',
            name='representante',
            field=models.CharField(max_length=255, verbose_name='Representante'),
        ),
        migrations.AlterField(
            model_name='sri',
            name='ruc',
            field=models.CharField(max_length=13, unique=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='sri',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='sri',
            name='usuario',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='supercom',
            name='contrasena',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='supercom',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='supercom',
            name='empresa',
            field=models.CharField(max_length=255, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='supercom',
            name='representante',
            field=models.CharField(max_length=255, verbose_name='Representante'),
        ),
        migrations.AlterField(
            model_name='supercom',
            name='ruc',
            field=models.CharField(max_length=13, unique=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='supercom',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='supercom',
            name='usuario',
            field=models.CharField(max_length=255, verbose_name='Usuario'),
        ),
    ]
