# Generated by Django 5.1.4 on 2025-04-18 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmanager', '0002_group_document_group_groupmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='collection', max_length=50, verbose_name='Icono')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collections/covers/', verbose_name='Imagen de portada')),
                ('color_code', models.CharField(default='#8B5CF6', max_length=20, verbose_name='Código de color')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token de compartición')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('include_annotations', models.BooleanField(default=True, verbose_name='Incluir anotaciones')),
                ('include_comments', models.BooleanField(default=False, verbose_name='Incluir comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_collections', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('view', 'Visualización'), ('export', 'Exportación'), ('share', 'Compartir'), ('print', 'Impresión'), ('edit', 'Edición'), ('add', 'Agregar documento'), ('remove', 'Quitar documento')], max_length=20, verbose_name='Tipo de actividad')),
                ('details', models.TextField(blank=True, verbose_name='Detalles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='docmanager.collection', verbose_name='Colección')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad de colección',
                'verbose_name_plural': 'Actividades de colecciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmanager.collection', verbose_name='Colección')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmanager.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Documento en colección',
                'verbose_name_plural': 'Documentos en colecciones',
                'ordering': ['order', 'created_at'],
                'unique_together': {('collection', 'document')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='documents',
            field=models.ManyToManyField(related_name='collections', through='docmanager.CollectionDocument', to='docmanager.document', verbose_name='Documentos'),
        ),
        migrations.CreateModel(
            name='CollectionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'Visualización'), ('edit', 'Edición'), ('admin', 'Administración')], default='view', max_length=20, verbose_name='Tipo de permiso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='docmanager.collection', verbose_name='Colección')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de colección',
                'verbose_name_plural': 'Permisos de colecciones',
                'unique_together': {('collection', 'user', 'permission_type')},
            },
        ),
    ]
