# Generated by Django 5.1.4 on 2025-03-12 06:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pandora', '0003_contactos'),
        ('products', '0013_remove_productprice_price_list_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_validez', models.PositiveSmallIntegerField(default=15, verbose_name='Días de Validez')),
                ('porcentaje_impuesto_default', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Impuesto Predeterminado')),
                ('texto_condiciones_pago', models.CharField(default='50% anticipo, 50% contra entrega', max_length=255, verbose_name='Texto de Condiciones de Pago')),
                ('texto_tiempo_entrega', models.CharField(default='5 días hábiles', max_length=255, verbose_name='Texto de Tiempo de Entrega')),
                ('notas_predeterminadas', models.TextField(blank=True, default='Precios incluyen IVA. Entrega en sus oficinas sin costo adicional dentro del perímetro urbano.', verbose_name='Notas Predeterminadas')),
                ('mostrar_logo', models.BooleanField(default=True, verbose_name='Mostrar Logo')),
                ('mostrar_descuento', models.BooleanField(default=True, verbose_name='Mostrar Descuento')),
                ('mostrar_impuesto', models.BooleanField(default=True, verbose_name='Mostrar Impuesto')),
                ('mostrar_codigos', models.BooleanField(default=True, verbose_name='Mostrar Códigos de Productos')),
                ('formato_moneda', models.CharField(default='$', max_length=10, verbose_name='Símbolo de Moneda')),
                ('decimales', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Decimales')),
                ('empresa_predeterminada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pandora.empresaclc', verbose_name='Empresa Predeterminada')),
            ],
            options={
                'verbose_name': 'Configuración de Proforma',
                'verbose_name_plural': 'Configuraciones de Proforma',
            },
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número de Proforma')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('atencion_a', models.CharField(blank=True, max_length=255, verbose_name='Atención a')),
                ('condiciones_pago', models.CharField(default='50% anticipo, 50% contra entrega', max_length=255, verbose_name='Condiciones de Pago')),
                ('tiempo_entrega', models.CharField(default='5 días hábiles', max_length=255, verbose_name='Tiempo de Entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Impuesto')),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('convertida', 'Convertida a Orden')], default='borrador', max_length=20, verbose_name='Estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas', to='pandora.clientes', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas', to='pandora.empresaclc', verbose_name='Empresa Emisora')),
                ('tipo_contratacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proformas', to='pandora.tipocontratacion', verbose_name='Tipo de Contratación')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProformaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('envio', 'Envío al cliente'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('conversion', 'Conversión a orden'), ('vencimiento', 'Vencimiento')], max_length=20, verbose_name='Acción')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, verbose_name='Estado Nuevo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_historial_created', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='proformas.proforma', verbose_name='Proforma')),
            ],
            options={
                'verbose_name': 'Historial de Proforma',
                'verbose_name_plural': 'Historiales de Proforma',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_item', models.CharField(choices=[('producto_ofertado', 'Producto Ofertado'), ('producto_disponible', 'Producto Disponible'), ('personalizado', 'Ítem Personalizado')], default='personalizado', max_length=50, verbose_name='Tipo de Ítem')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('unidad', models.CharField(default='Unidad', max_length=50, verbose_name='Unidad')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('producto_disponible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_items', to='products.productodisponible', verbose_name='Producto Disponible')),
                ('producto_ofertado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_items', to='products.productoofertado', verbose_name='Producto Ofertado')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proformas.proforma', verbose_name='Proforma')),
            ],
            options={
                'verbose_name': 'Ítem de Proforma',
                'verbose_name_plural': 'Ítems de Proforma',
                'ordering': ['proforma', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['numero'], name='proformas_p_numero_30261c_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['fecha_emision'], name='proformas_p_fecha_e_d62e35_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['estado'], name='proformas_p_estado_861ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='proformaitem',
            index=models.Index(fields=['proforma', 'orden'], name='proformas_p_proform_0eb801_idx'),
        ),
    ]
