# Generated by Django 5.1.4 on 2025-02-19 07:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pandora', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Number')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('payment_terms', models.CharField(max_length=200, verbose_name='Payment Terms')),
                ('delivery_time', models.CharField(max_length=100, verbose_name='Delivery Time')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Tax')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Total')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='Terms and Conditions')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas', to='pandora.clientes', verbose_name='Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_proformas', to=settings.AUTH_USER_MODEL)),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_proformas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='proformas.proforma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proforma History',
                'verbose_name_plural': 'Proforma History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(help_text='Cantidad debe ser mayor a 0', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario debe ser mayor o igual a 0', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento entre 0 y 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proformas.proforma')),
            ],
            options={
                'verbose_name': 'Proforma Item',
                'verbose_name_plural': 'Proforma Items',
            },
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['-created_at'], name='proformas_p_created_52f3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['number'], name='proformas_p_number_45e20e_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['status'], name='proformas_p_status_6f5880_idx'),
        ),
        migrations.AddIndex(
            model_name='proformahistory',
            index=models.Index(fields=['-created_at'], name='proformas_p_created_44a751_idx'),
        ),
        migrations.AddIndex(
            model_name='proformahistory',
            index=models.Index(fields=['action'], name='proformas_p_action_4cb85a_idx'),
        ),
    ]
