# Generated by Django 5.1.4 on 2025-03-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre descriptivo'),
        ),
    ]
