# Generated by Django 5.1.4 on 2025-04-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0002_add_nombre_to_proforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número de Proforma'),
        ),
    ]
