# Generated by Django 5.1.4 on 2025-04-22 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandora', '0004_clientes_nota_relacionesblue'),
        ('proformas', '0004_add_secuencia_proforma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='secuenciaproforma',
            new_name='proformas_s_anio_531dc9_idx',
            old_name='proformas_s_anio_65f04e_idx',
        ),
        migrations.AddConstraint(
            model_name='proforma',
            constraint=models.UniqueConstraint(fields=('numero',), name='unique_proforma_numero'),
        ),
    ]
