# Generated by Django 5.1.4 on 2025-03-17 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pandora', '0003_contactos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('origen', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('presupuestoref', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pandora.clientes')),
            ],
            options={
                'verbose_name': 'Brief',
                'verbose_name_plural': 'Briefs',
                'ordering': ['-fecha', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='BriefItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cudim', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_brief', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='brief.brief')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pandora.unidades')),
            ],
            options={
                'verbose_name': 'Brief Item',
                'verbose_name_plural': 'Brief Items',
                'ordering': ['id_brief', 'nombre'],
            },
        ),
    ]
